### ISSUE TITLE
Complete design specification for date range option

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-datepicker#104]
## Is your feature request related to a problem? Please describe.

There is an existing design file for a date range feature. 

## Describe the solution you'd like

This file needs to be completed and presented to the engineers in order to finalize the requested development spec.

**Comment by leeejune** [comment]
Date range specs are outlined here: https://www.figma.com/file/mZzZNE0cEPnphZozbaZfDy/Calendar?node-id=1839%3A23842&t=gkfCMlaUKKa7v6F3-1
