### ISSUE TITLE
As a Developer I need help with extending the current calendar and Table(Sorting and Design Customization) components

### ISSUE THREAD

**Issue by rahulanand87** [AlaskaAirlines/auro-datepicker#114]
# General Support Request

## Support request

Not able to customize the individual days in the calendar to show extra information, please refer to the attached screenshot from Jill (UI/UX) designer for our project (Crew PBS GDO). 

## Possible Solution
Calendar should provide options to fully customize the calendar and individual days in terms of their style and to indicate some extra information such as holiday or bids left. Like styling the days to show holiday status and bids capacity number. User need to be restricted while making the selection of bid days in block of 2 or 3 continuous days only.

## Context

We are trying to create a new project(driven by UI/UX designer Jill) and has been advised to use the Auro design and components. We would like to get some help to understand the components and be inline with other products using Auro design and components.
Link to UI/UX design: 
https://www.figma.com/file/VlPZKdRMLyKDxcunD4oJ4B/Golden-Days-Off?node-id=155%3A46156&t=hCxjJMdMpnZgwNmj-1

## Your Environment

Angular 14

* Version used: latest
* Browser Name and version: Safari
* Operating System and version (desktop or mobile): IPad
* Link to your project: https://github.com/Alaska-ITS/PBS/tree/feature/sprint-7/GDO/WebSvc/WebUI/GoldenDaysOff.UI

![image](https://user-images.githubusercontent.com/85928017/229191424-cb3c5ddb-675a-447d-b159-4548206709ec.png)

**Comment by blackfalcon** [comment]
Issue has been reviewed and will consult with the team.
