### ISSUE TITLE
Icons are being loaded from unpkg even when installed locally

### ISSUE THREAD

**Issue by jeremeevans** [AlaskaAirlines/auro-datepicker#116]
## Describe the bug

The date-picker is loading icons from unpkg even when the date-picker and supporting resources are installed locally. Found because unpkg is currently giving a CORS error for requests from localhost:
<img width="671" alt="image" src="https://user-images.githubusercontent.com/1747006/229853803-f313a441-9e9c-4612-b068-9c5ba08b1993.png">

## To Reproduce

1. Install date-picker and supporting resources locally, -D
2. Add them to an index.html, for example:
    <img width="615" alt="image" src="https://user-images.githubusercontent.com/1747006/229854168-8725a2ed-8b13-4115-bfad-f4aacfbfd4a7.png">
3. drop a date picker on it, and run it locally

## Expected behavior

Icons should be loaded from node_modules

## Screenshots

See above...

## Desktop (please complete the following information):

 - OS: Mac
 - Browser Firefox
 - Version 111.0.1

**Comment by blackfalcon** [comment]
@jason-capsule42 can we get this addressed in the current date range updates you are working on? 

## Exit criteria 

Components should not be using auro-icon as an icon resource. See preferred install method. https://github.com/AlaskaAirlines/Icons#lit-element
