### ISSUE TITLE
Update to use Chalk 5

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-datepicker#119]
# General Support Request

Repos are using a legacy version fo Chalk that requires an integration change of the code. 

## Support request

Update to the latest version of Chalk and address similar updates as done in this commit 

- https://github.com/AlaskaAirlines/auro-input/pull/253/commits/b0bc88832a1345011cf6fae3d78c11f76a8e8e32

## Exit criteria 

This issue is closed once the repo can be built using the latest version of. Chalk.

**Comment by jordanjones243** [comment]
This issue was addressed in this PR, but had not yet been reflected in the PR's notes:
- https://github.com/AlaskaAirlines/auro-datepicker/pull/112
