### ISSUE TITLE
Slot content below date

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-datepicker#128]
## Is your feature request related to a problem? Please describe.

We want the ability to show prices or text on the calendar below each date.

## Describe the solution you'd like

A slot to add content below each date.  And the ability to change the color of this depending on the use case.
At Screen Size of 320px and below, font size is the smallest font size (xxs design token).  Larger screens get a larger size (xs design token).
A "Part" attribute is added to the slot so that it can be styled.

## Describe alternatives you've considered

Not showing content below the date.
Popover will be handled in another story.

**Comment by leeejune** [comment]
After consulting @erikalanghauser, @yvonneyamasaki, and Kayla, we have decided on this solution. We will be discussing this solution on 10/2's meeting.

This screenshot shows an example of a sold out date (9/9) and a day with no flights at all (9/28). When the user hovers over these dates on desktop/selects these dates on mobile, a popover appears to show more context of why the date is unavailable.

![Screenshot 2023-09-28 at 4 49 43 PM](https://github.com/AlaskaAirlines/auro-datepicker/assets/55998746/c24a7c89-d646-4be0-aae4-79902e57f3e2)
