### ISSUE TITLE
AScom cannot import bundled assets on legacy circumstances

### ISSUE THREAD

**Issue by gusnaughton** [AlaskaAirlines/auro-datepicker#129]
### Please verify the version of wc-generator you have installed

3.1.2

### Please describe the bug

Anil Krishna is looking to import the auro-datepicker into the homelet on the AScom homepage.

He has added the following lines to AScom:

```
<script src="[https://unpkg.com/@('@')aurodesignsystem/auro-combobox@latest/dist/auro-combobox__bundled.js"](https://unpkg.com/@(%27@%27)aurodesignsystem/auro-combobox@latest/dist/auro-combobox__bundled.js%22) type="module"></script>
<script src="[https://unpkg.com/@('@')aurodesignsystem/auro-datepicker@2.0.0/dist/auro-datepicker__bundled.js"](https://unpkg.com/@(%27@%27)aurodesignsystem/auro-datepicker@2.0.0/dist/auro-datepicker__bundled.js%22) type="module"></script>
<script src="[https://unpkg.com/@('@')alaskaairux/auro-icon@latest/dist/auro-icon__bundled.js"](https://unpkg.com/@(%27@%27)alaskaairux/auro-icon@latest/dist/auro-icon__bundled.js%22) type="module"></script>
<script src="[https://unpkg.com/@('@')aurodesignsystem/auro-calendar@latest/dist/auro-calendar__bundled.js"](https://unpkg.com/@(%27@%27)aurodesignsystem/auro-calendar@latest/dist/auro-calendar__bundled.js%22) type="module"></script>

        <script src="[https://unpkg.com/@('@')alaskaairux/auro-button@latest/dist/auro-button__bundled.js"](https://unpkg.com/@(%27@%27)alaskaairux/auro-button@latest/dist/auro-button__bundled.js%22) type="module"></script>
<script src="[https://unpkg.com/@('@')aurodesignsystem/auro-dropdown@latest/dist/auro-dropdown__bundled.js"](https://unpkg.com/@(%27@%27)aurodesignsystem/auro-dropdown@latest/dist/auro-dropdown__bundled.js%22) type="module"></script>
<script src="[https://unpkg.com/@('@')aurodesignsystem/auro-input@latest/dist/auro-input__bundled.js"](https://unpkg.com/@(%27@%27)aurodesignsystem/auro-input@latest/dist/auro-input__bundled.js%22) type="module"></script>
```

This results in none of the unpkg-imported components to be registered to the customElements registry.
![image](https://github.com/AlaskaAirlines/WC-Generator/assets/7005799/04f56e89-dc95-43ad-a59d-ac461135838e)

### Reproducing the error

This issue cannot be reproduced on the Auro docsite

### Expected behavior

Expected behavior: running customElements.get('auro-calendar') and all other unpkg-imported components from the homelet returns a valid component function. Currently, it returns undefined and elements cannot be used in the experience.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Additional context

Please contact @anikris1 for more details.

### Exit criteria

Homelet can use the calendar and combobox.

**Comment by blackfalcon** [comment]
@jason-capsule42 I am punting this issue to you as this appears to be a problem caused by incorrect CDN install instructions. 

Auro Datepicker is working on the Auro docsite using the CDN assets, so we have high confidence that this element will work when used from a CDN. 

I highly recommend that you use `https://cdn.jsdelivr.net/npm` as the CDN source and DO NOT use `@latest` as this is very dangerous and opens your project up for failure if we roll out a MAJOR change or release new code with a bug.

**Comment by blackfalcon** [comment]
@jason-capsule42 is there a status update on this issue?
