### ISSUE TITLE
Can't resolve './src/auro-calendar'

### ISSUE THREAD

**Issue by anikris1** [AlaskaAirlines/auro-datepicker#131]
## Describe the bug

![image](https://github.com/AlaskaAirlines/auro-datepicker/assets/128737524/f08c5f06-e6dc-4906-9b69-feaa997f817c)

## To Reproduce

npm i

## Expected behavior

npm pass

## Screenshots
![image](https://github.com/AlaskaAirlines/auro-datepicker/assets/128737524/4ecf5b57-844d-4893-92ac-123626b10689)

**Comment by jason-capsule42** [comment]
This is an invalid bug that was created due to a misunderstanding of the documentation.

I am closing this issue out.
