### ISSUE TITLE
Calendar back button unexpected visibility

### ISSUE THREAD

**Issue by arrenleung** [AlaskaAirlines/auro-datepicker#136]
## Describe the bug

- When instantiating a datepicker with a minDate and value that fall within the same month (e.g., minDate="07/01/2023" and value="07/15/2023"), the calendar displays a back button to navigate to the previous month.
  - The button is interactable and will throw the calendar into an uninteractable state when selected.
  - Navigating forward a month and then navigating back removes the button
  - Does not occur when using the range attribute

## To Reproduce

1. Go to https://www.alaskaair.com/search-test/
1. Click on either departing or returning datepicker to open the calendar popover
1. See that the back month navigation button is visible
1. Navigate back a month
1. See that you cannot navigate forward again nor select any dates since they are < minDate

## Expected behavior

- The calendar popover does not show the back month navigation button when creating a datepicker with minDate and value in the same month

## Screenshots

- On first load:

<img width="1163" alt="image" src="https://github.com/AlaskaAirlines/auro-datepicker/assets/43892293/8796a0d9-3156-4e0f-963c-475f4d26235e">

- When presssing back button:

<img width="1161" alt="image" src="https://github.com/AlaskaAirlines/auro-datepicker/assets/43892293/1e2a31e2-caec-48d1-a7f5-49a24f937215">

## Desktop:

 - OS: MacOS 13.4.1 (22F82)
 - Browser: Occurs on Chrome, Safari, and Firefox
 - Version: N/A

**Comment by blackfalcon** [comment]
Verified.
