### ISSUE TITLE
Revamp mobile layout to account for device address/search bar and keyboard

### ISSUE THREAD

**Issue by arrenleung** [AlaskaAirlines/auro-datepicker#140]
## Describe the bug

When the calendar full-page modal is viewed on mobile Safari browsers, the close button is covered by the search bar when users scroll.

## To Reproduce

1. Go to https://www.alaskaair.com/search-test-1235/ on a mobile Safari browser
1. Click on the datepicker to open the calendar
1. Scroll in any direction (if the search bar is not expanded)
1. See that the close button is covered by the search bar

## Expected behavior

The close button is aware of the dynamic viewport and shifts accordingly.

## Screenshots

![image](https://github.com/AlaskaAirlines/auro-datepicker/assets/43892293/8a408318-55fa-48c8-ab87-38f31c95f9ff)

## Smartphone (please complete the following information):

 - Device: iPhone 14 Pro
 - OS: iOS 16.6
 - Browser: Safari
 - Version: 16(?)

**Comment by Patrick-Daly-AA** [comment]
Reproduces on Android Chrome mobile browser as well.

**Comment by braven112** [comment]
Notes from refinement:
Should we look at how we handle modal's and match that experience?

**Comment by leeejune** [comment]
After discussing with the engineers, we've decided to make these changes:

- Fix cursor focus behavior
- Reduce whitespace on top of "close" button to 150px from 200px
- Apply gradient to whitespace (issue #)
- Repositioning component elements based on address bar and keyboard display

Blueprint has been edited to reflect these changes. Refer to the screenshots below for updated areas of the blueprint.
https://www.figma.com/file/mZzZNE0cEPnphZozbaZfDy/Calendar?type=design&node-id=2714-36971&mode=design&t=ZcA0yVpXFhPDDJ33-11

![Screenshot 2023-09-28 at 12 26 41 PM](https://github.com/AlaskaAirlines/auro-datepicker/assets/55998746/d0e02dda-67a8-4e89-9ca2-3d62a438ebc8)
![Screenshot 2023-09-28 at 12 26 28 PM](https://github.com/AlaskaAirlines/auro-datepicker/assets/55998746/665074b7-982e-4a23-a8fc-5551796d1da1)
![Screenshot 2023-09-28 at 12 26 24 PM](https://github.com/AlaskaAirlines/auro-datepicker/assets/55998746/a49c9071-33b5-4b20-9654-93713cd64aab)

**Comment by Patrick-Daly-AA** [comment]
From our investigations, mobile devices do not actually expose to the web page whether a keyboard is open or not.  Thus supporting the layout adapting to keyboard being present or not is not something possible at this time.
