### ISSUE TITLE
MOW: Date panes off-center

### ISSUE THREAD

**Issue by arrenleung** [AlaskaAirlines/auro-datepicker#141]
## Describe the bug

Two minor visual bugs that I'd rather wrap into one issue:

1. On mobile devices (not on desktop mobile breakpoints), the selected date panes are slightly off-center with the date number
2. On mobile devices and desktop mobile breakpoints, the calendar gradient is not visible and cuts off to white instead

## To Reproduce

Steps to reproduce:

1. Go to https://auro.alaskaair.com/components/auro/datepicker on a mobile device's browser (reproducible on Chrome and Safari so far)
2. See bug (2) below the calendar
3. Select either the single or range datepicker
4. Select a date
5. See bug (1)

## Expected behavior

- Selected date panes are centered with date numbers on mobile devices
- There is a gradient that extends to the close button as seen in the [design doc](https://www.figma.com/file/mZzZNE0cEPnphZozbaZfDy/Calendar?type=design&node-id=1839-23842&mode=design&t=lT9aI0mZ8dZmjWNH-0):
    <img width="438" alt="image" src="https://github.com/AlaskaAirlines/auro-datepicker/assets/43892293/eba9854d-2a81-43eb-b7f2-64f740e7f4a2">

## Screenshots

![IMG_E8DF63AA1634-1](https://github.com/AlaskaAirlines/auro-datepicker/assets/43892293/8d46f897-dece-49c2-9cb4-d17a2b40c340)

## Smartphone:

 - Device: iPhone 14 Pro
 - OS: iOS 16.6
 - Browser: Safari 16, Chrome 116.0.5845.90

**Comment by jason-capsule42** [comment]
Gradient will be handled as part of this issue: [Revamp mobile layout to account for device address/search bar and keyboard](https://github.com/AlaskaAirlines/auro-datepicker/issues/140)
