### ISSUE TITLE
Remove auro-icon Dependency?

### ISSUE THREAD

**Issue by isaiahscheel** [AlaskaAirlines/auro-datepicker#144]
# General Support Request
Not urgent, can wait/discuss especially for more solid example.

The flight search team has gotten a few reports that the arrows on the date picker are not rendering for some guests. Unfortunately we do not have QM replays or screenshots, but this makes searching for a flight sometimes impossible if they need to switch dates.

## Support request

My request is to not rely on auro-icon because there is a network call that is downloading these icons and this may be causing some issues

## Possible Solution

Seems like there is a precedent for not using auro-icon component here: 
https://github.com/AlaskaAirlines/auro-carousel/pull/8 

## Context

I know there has been a lot of updates to datepicker and the contract changed a bit recently as well with centralDate that we had to mess with, so this is just a suggestion and something we wanted auro to be aware of that we were getting reports. 

## Your Environment

* Version used: N/A
* Browser Name and version: N/A
* Operating System and version (desktop or mobile): N/A
* Link to your project: https://github.com/Alaska-ECommerce/flightsearch-lem-svelte/blob/b7419f96446317d6616d5540483854c32933361c/src/lib/planbook/DateTimePicker.svelte#L91

**Comment by blackfalcon** [comment]
I agree, the following code should be updated to have icons as an internal dependency for the project and the icon be shipped as part of the element's bundle. 

https://github.com/AlaskaAirlines/auro-datepicker/blob/88392438c76c7c069c300d7660eb17b54abf695e/src/auro-calendar.js#L312-L314
