### ISSUE TITLE
Datepicker in Angular App

### ISSUE THREAD

**Issue by Apsistec** [AlaskaAirlines/auro-datepicker#146]
## Describe the bug
We are using most of the available auro packages for our desktop app, although we just started using auro about three weeks ago. We have been able to use most of the packages, but the datepicker is not working. The errors are:
./node_modules/@aurodesignsystem/auro-datepicker/index.js:1:0-51 - Error: Module not found: Error: Can't resolve './src/auro-calendar' in '/Users/Douglas.White7@alaskaair.com/Dev/RampApp/node_modules/@aurodesignsystem/auro-datepicker'

./node_modules/@aurodesignsystem/auro-datepicker/index.js:2:0-62 - Error: Module not found: Error: Can't resolve './src/auro-calendar-month' in '/Users/Douglas.White7@alaskaair.com/Dev/RampApp/node_modules/@aurodesignsystem/auro-datepicker'

./node_modules/@aurodesignsystem/auro-datepicker/index.js:3:0-60 - Error: Module not found: Error: Can't resolve './src/auro-calendar-cell' in '/Users/Douglas.White7@alaskaair.com/Dev/RampApp/node_modules/@aurodesignsystem/auro-datepicker'

./node_modules/@aurodesignsystem/auro-datepicker/index.js:4:0-55 - Error: Module not found: Error: Can't resolve './src/auro-datepicker' in '/Users/Douglas.White7@alaskaair.com/Dev/RampApp/node_modules/@aurodesignsystem/auro-datepicker'

## To Reproduce

1. Go to 'RampApp'
1. Install monorepo 
1. Run nx serve admin
1. See error

## Expected behavior

Expect to see modal of calendar when clicking on Form field.

## Screenshots
src directory is in the root directory in other auro packages, but not in datepicker (see images)
![image](https://github.com/AlaskaAirlines/auro-datepicker/assets/6438623/01253f87-eb64-44ef-9376-7a6852a65d45)
![image](https://github.com/AlaskaAirlines/auro-datepicker/assets/6438623/9b9ae7da-4e18-4468-96e3-ab78d7c7a208)

## Desktop (please complete the following information):

 - OS: [e.g. iOS] MacOS
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22]116.0.5845.110

## Additional context
From what I can see the src folder is missing from the root directory, and instead it is in the dist folder; where in other packages the src folder is in the root directory and and not in the dist folder.  The error says that './src/auro-several-things' can not be found, and that is b/c src does not exist in the root folder....

**Comment by blackfalcon** [comment]
VALIDATED: You can see the package internals here https://www.runpkg.com/?@aurodesignsystem/auro-datepicker@2.0.6/index.js

https://github.com/AlaskaAirlines/auro-datepicker/blob/88392438c76c7c069c300d7660eb17b54abf695e/.npmignore#L21-L24

I believe that is was stated in another conversation that the bundled version didn't work either? That's confusing as we are using the `@latest` bundled version in the doc site. The fix is pretty straight forward, we need to update the `.npmignore` to be like the linked template. 

https://github.com/AlaskaAirlines/WC-Generator/blob/master/template/.npmignore.temp

**Comment by blackfalcon** [comment]
@Apsistec I have created a PR that I am hoping will address the install issue you are seeing. @jason-capsule42 if you could do a review of this update so that we can test this ASAP would be appreciated.

**Comment by Apsistec** [comment]
Nice! Thank you!

Best regards,

Douglas White
***@***.******@***.***>
512.293.1045

From: Dale Sande ***@***.***>
Date: Monday, August 28, 2023 at 8:03 PM
To: AlaskaAirlines/auro-datepicker ***@***.***>
Cc: Douglas White ***@***.***>, Mention ***@***.***>
Subject: Re: [AlaskaAirlines/auro-datepicker] Datepicker in Angular App (Issue #146)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>
[EXTERNAL SENDER]


@Apsistec<https://github.com/Apsistec> I have created a PR that I am hoping will address the install issue you are seeing. @jason-capsule42<https://github.com/jason-capsule42> if you could do a review of this update so that we can test this ASAP would be appreciated.

**Comment by Apsistec** [comment]
Thank you!
