### ISSUE TITLE
Gradient on bottom of calendar missing

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/auro-datepicker#150]
## Describe the bug

The bottom part of the calendar should be in a gradient. Currently it is a solid white color.

## To Reproduce

1. Go to https://auro.alaskaair.com/components/auro/datepicker
2. Click on the datepicker
3. See error

## Expected behavior
Specs are listed out in this blueprint: https://www.figma.com/file/mZzZNE0cEPnphZozbaZfDy/Calendar?type=design&node-id=1839-23842&mode=design&t=vvzqoI7BimOAHXeK-11

![Screenshot 2023-09-29 at 11 04 51 AM](https://github.com/AlaskaAirlines/auro-datepicker/assets/55998746/14a6bcdd-d382-4b9d-80c1-09af5d85d4eb)

![Screenshot 2023-09-29 at 11 04 56 AM](https://github.com/AlaskaAirlines/auro-datepicker/assets/55998746/5afc30d8-d063-4753-b1ec-950a5e9ac40a)

## Additional context
This issue is related to issue #140

**Comment by yvonneyamasaki** [comment]
Changed Height of the gradient


![Image](https://github.com/AlaskaAirlines/auro-datepicker/assets/144830559/ff00785b-44aa-414c-b62e-7fe201e9fcc6)



![Image](https://github.com/AlaskaAirlines/auro-datepicker/assets/144830559/579bff90-82c6-4d81-8ac3-cf4e3bba1668)


Specs are listed out in this blueprint:
https://www.figma.com/file/r0xy9TpWpR0AQ6to1dQ9gY/Date-Picker?type=design&node-id=740-29915&mode=design&t=lTpPrQPfYg5VRg37-4
