### ISSUE TITLE
mobile datepicker UI updates

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-datepicker#154]
## Is your feature request related to a problem? Please describe.

There are a few ui issues with the current mobile design of the calendar.  

## Describe the solution you'd like

We have a new blueprint with some new designs that can be found here:  https://www.figma.com/file/r0xy9TpWpR0AQ6to1dQ9gY/Date-Picker

Some of the highlights are we remove the back icon in the upper left.
We will have one full screen "done" button at the bottom of the screen.

## Describe alternatives you've considered

None

## Additional context

Part of our larger mobile redesign [milestone ](https://github.com/AlaskaAirlines/auro-datepicker/milestone/8)

AC:
Back button in mobile experience is removed
one full screen width button to apply changes at the bottom.
Mobile responsive design implementation (320px) (#151 )
Re-Add Gradient to bottom of Calendar (#150 )
Popover on Entire Date (#153 )

**Comment by Patrick-Daly-AA** [comment]
<img width="359" alt="Screenshot 2023-11-07 at 12 05 17 PM" src="https://github.com/AlaskaAirlines/auro-datepicker/assets/128407248/3cdee950-a2ef-4889-94b2-8485075a88cd">
<img width="830" alt="Screenshot 2023-11-07 at 12 05 13 PM" src="https://github.com/AlaskaAirlines/auro-datepicker/assets/128407248/28185d7b-5335-40f8-bbc4-69327f178f12">
<img width="504" alt="Screenshot 2023-11-07 at 12 04 42 PM" src="https://github.com/AlaskaAirlines/auro-datepicker/assets/128407248/b6c7c9d7-a988-484a-a582-bc530277e4cf">
