### ISSUE TITLE
auro-datepicker: Addressing the CSS parts inside the date picker. 

### ISSUE THREAD

**Issue by aledgarfuentes** [AlaskaAirlines/auro-datepicker#156]
## Describe the bug

auro-datepicker does not have CSS parts to modify the style, in the same way that it is currently in auro input and other auro components.

## Expected behavior

Allow to modify the style of auro-datepicker the same way it is available for other auro components CSS parts.

## Screenshots

E.g. Auro input

![image](https://github.com/AlaskaAirlines/auro-datepicker/assets/96540698/111378bd-9285-4f58-9554-878287a3e242)

![image](https://github.com/AlaskaAirlines/auro-datepicker/assets/96540698/020b0c83-929c-4716-b151-7237b9a12d20)

**Comment by blackfalcon** [comment]
The proposed solution is good. 

### Exit Criteria 

This issue can be closed once there is a demonstratable option for end users to customize the look of the baseline element via CSS Parts.
