### ISSUE TITLE
auro-datepicker overrides auro-input to older version

### ISSUE THREAD

**Issue by ethanwmiller** [AlaskaAirlines/auro-datepicker#163]
## Describe the bug

When using auro-datepicker and auro-input in the same codebase, auro-datepicker is causing auro-input to behave incorrectly. This is due to auro-datepicker having a dependency on an older version of auro-input, which for some reason is overriding the specified auro-input import.

Specifically, auro-input version 2.15.x is needed, but auro-datepicker is causing auro-input version 2.14.x to appear. The bump to 2.15 fixed a specific bug in the input that we need in our codebase. From this github issue: https://github.com/AlaskaAirlines/auro-input/issues/265

NOTE: this can be circumvented by importing auro-input _before_ auro-datepicker, but as per @jason-capsule42 this should still be open so that effort to update auro-datepicker's dependency methods can be tracked. Thanks

## To Reproduce

1. Import auro-datepicker and auro-input in the same codebase.
2. Create an input with a label
3. Type something into the input
4. Programmatically clear the input via a click handler function that sets the input value to `undefined`.
5. The input value will clear, but the input's label will not reset.
6. Remove auro-datepicker import from the codebase and refresh.
7. Do step 4 again
8. This time the input will behave as expected.

## Expected behavior

Either auro-datepicker should not override other versions of auro-input in the same codebase, or auro-datepicker's input dependency should be updated.

## Screenshots

<img width="578" alt="Screen Shot 2023-11-08 at 11 07 51 AM" src="https://github.com/AlaskaAirlines/auro-datepicker/assets/126627409/65b19856-4086-4b2d-98b6-f49348f10511">

When auro-datepicker is imported in the codebase, the bug from auro-input issue 265 can be seen (label not resetting after value is cleared).

## Desktop (please complete the following information):

 - OS: Mac OS
 - Browser: Chrome
 - Version: 119

## Smartphone (please complete the following information):

N/A

## Additional context

We are using the CDN for both imports.

**Comment by blackfalcon** [comment]
@jason-capsule42 a couple of things here. 

1. With the release of these updates https://github.com/AlaskaAirlines/auro-datepicker/pull/158 and updating all the dependencies to @latest that should resolve this issue? 
2. To keep this from happening in the future, should we not use the extension pattern to avoid version conflicts?

**Comment by blackfalcon** [comment]
Can we review and re-validate if this is still an issue?

**Comment by Patrick-Daly-AA** [comment]
@blackfalcon will revalidate along with some other investigation he's got underway shortly.

**Comment by jordanjones243** [comment]
The work to fix this issue is related to this issue:
- https://github.com/AlaskaAirlines/auro-datepicker/issues/166
