### ISSUE TITLE
Explore Mobile Date picker where first rendered month is always min date (if min date is declared)

### ISSUE THREAD

**Issue by Patrick-Daly-AA** [AlaskaAirlines/auro-datepicker#165]
Investigate the proposal in the title as a possible fix to #152 

Will need a follow-up to automagically scroll to selected date if one is pre-set to more comprehensively improve the UX.

**Comment by blackfalcon** [comment]
Is it possible to bind this to the following milestone? 

- https://github.com/AlaskaAirlines/auro-datepicker/milestone/8

**Comment by Patrick-Daly-AA** [comment]
Confirmed issue is fixed.
