### ISSUE TITLE
Update DatePicker to load it's own version of Auro Input, similar to how ComboBox handles this

### ISSUE THREAD

**Issue by Patrick-Daly-AA** [AlaskaAirlines/auro-datepicker#166]
## Describe the bug

There are build issues when a page uses the latest version of Auro Input, and has Datepicker on it, since DatePicker uses a slightly older version of Auro Input/

## To Reproduce

1. Make a page with Auro Input and DatePicker
1. Attempt to build the page

## Expected behavior

Build is successful

## Additional context

To Be solved the way that we solved this issue with Combobox: https://github.com/AlaskaAirlines/auro-combobox/issues/127

**Comment by blackfalcon** [comment]
See issue for additional context 

- https://github.com/AlaskaAirlines/auro-datepicker/issues/163
