### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'slice')

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-datepicker#169]
## Describe the bug

When running the datepicker in the docsite, there is a JS error that appears in the console. This appears to not be causing any functional issues that are visually noticeable. 

## To Reproduce

1. Go to https://auro.alaskaair.com/components/auro/datepicker
1. Open the inspector console
1. Click on the BASIC example datepicker example 
1. Select any date
1. See the error in the console 

```
auro-datepicker__bundled.js:14814 Uncaught TypeError: Cannot read properties of undefined (reading 'slice')
at Object.getPostDelimiter (auro-datepicker__bundled.js:14814:26)
at Cleave.onChange (auro-datepicker__bundled.js:15343:34)
at AuroInput.notifyValueChanged (auro-datepicker__bundled.js:16230:10)
at AuroInput.updated (auro-datepicker__bundled.js:16113:14)
at AuroInput._$AE (auro-datepicker__bundled.js:12:5221)
at AuroInput.performUpdate (auro-datepicker__bundled.js:12:5000)
at AuroInput.scheduleUpdate (auro-datepicker__bundled.js:12:4581)
at AuroInput._$Ej (auro-datepicker__bundled.js:12:4489)
at async AuroInput._$Ej (auro-datepicker__bundled.js:12:4431)
```

## Expected behavior

Console error should not appear when executing functionality 

## Screenshots

<img width="1231" alt="Screen Shot 2023-11-29 at 12 03 15 PM" src="https://github.com/AlaskaAirlines/auro-datepicker/assets/181089/0995aad2-a7f3-4890-8f6b-02861aa1f883">

## Desktop (please complete the following information):

 - OS: [macOS]
 - Browser [Chrome]
 - Version [@latest]

## Exit criteria 

This issue can be closed once a user can execute the element's feature that not see an error in the console.

**Comment by jordanjones243** [comment]
This error is coming from cleave js from within `auro-input` and is not something we can fix within our own code. The issue was addressed here, but seems like this fix is no longer valid:

https://github.com/AlaskaAirlines/auro-input/issues/238
https://github.com/AlaskaAirlines/auro-input/pull/256

**Comment by blackfalcon** [comment]
@jordanjones243 can you please validate if this is still an issue. If it is, please comment, in some detail, as to what was tried to resolve and a potential resolution to address.

**Comment by Patrick-Daly-AA** [comment]
Requires further investigation to see if this is fixable.  Current theory is that Cleave JS is trying to format the text before there is any text.

**Comment by Patrick-Daly-AA** [comment]
Determined that this is not worth the issue to fix so long as we are using CleaveJS
