### ISSUE TITLE
Really large empty space under calendar choices 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-datepicker#173]
## Describe the bug

When using the date picker in mobile view, there is a really large empty space below the selectable calendar dates and the foot of the view. 

## To Reproduce

1. Go to https://auro.alaskaair.com/components/auro/datepicker#gsc.tab=0
1. Either do this on a mobile device or be in mobile mode for your browser 
1. Click into the datepicker and scroll
1. See error

## Expected behavior

The UI of selectable dates should take up more of the usable space in the UI. 

<img width="364" alt="Screen Shot 2023-12-08 at 11 05 06 AM" src="https://github.com/AlaskaAirlines/auro-datepicker/assets/181089/bfd12d1f-5dde-456f-a816-247b30f60708">

https://www.figma.com/file/r0xy9TpWpR0AQ6to1dQ9gY/Date-Picker?type=design&node-id=2539-83349&mode=design&t=R0G3aAL0mKX8o2WI-0

## Screenshots

![Screen Shot 2023-12-08 at 10 57 42 AM](https://github.com/AlaskaAirlines/auro-datepicker/assets/181089/70001b0b-9853-4249-b3d6-ecde4a2732b6)

## Desktop (please complete the following information):

 - OS: [macOS and iOS]
 - Browser [chrome and safari]
 - Version [@latest]

## Exit criteria 

This issue can be closed once the issue has been corrected and matches the defined UI spec.

**Comment by jason-capsule42** [comment]
This is part of the intended design. All calendars render 6 rows even if the grid flow would fit on 5. This was decided by design team during initial build of the component. Reference @leeejune for more information.

**Comment by Patrick-Daly-AA** [comment]
An improvement to this issue has been included in the linked PR addressing a different issue.  A full re-visit of this behavior will be considered for the next major version of DatePicker.

**Comment by blackfalcon** [comment]
See issue 

- https://github.com/AlaskaAirlines/auro-datepicker/issues/154
