### ISSUE TITLE
mobile: calendar unable to go past current month of the year

### ISSUE THREAD

**Issue by cynthiaricomendoza-alaskaair** [AlaskaAirlines/auro-datepicker#174]
## Describe the bug

when the minDate is set to a date in the past and the maxDate is set to today's date, the calendar drop down does not allow the user to choose dates before the current month. the calendar only allows users to scroll through future dates which are disabled because the maxDate is set to today's date.

here is an example of what our code looks like:
```html
        <auro-datepicker
          id="birth-date"
          setCustomValidityValueMissing="Infant's birthdate is required."
          ${ref(this.liBirthdayRef)}
          @auroDatePicker-valueSet=${this.birthdaySelected}
          maxDate="12/13/2023"
          minDate="12/14/2021"
          setCustomValidityRangeUnderflow="Each child 2 years and older must have their own seat and ticket."
          required
        >
          <span slot="fromLabel"
            >Birth date</span
          >
          <span slot="mobileDateLabel"
            >Birth date</span
          >
        </auro-datepicker>
```

## To Reproduce

1. Set the minDate on the auro-datepicker to a date in the past, (e.g. 2021-12-12)
2. Set the maxDate on the auro-datepicker to today's date
3. In mobile, click on the auro-datepicker and observe you are unable to scroll through dates past the current month of the year.

## Expected behavior

In mobile, the calendar in the auro-datepicker should allow the user to scroll through dates in the past if the minDate is set to a date in the past.

## Screenshots

https://github.com/AlaskaAirlines/auro-datepicker/assets/116121736/23551307-d3e5-4a74-a4d0-098b40cedbed

## Desktop (please complete the following information):

 - OS: macOS
 - Browser Chrome
 - Version

**Comment by blackfalcon** [comment]
@jordanjones243 can you follow up on this? I feel that this is possibly being addressed with the upcoming release work?

**Comment by jordanjones243** [comment]
> @jordanjones243 can you follow up on this? I feel that this is possibly being addressed with the upcoming release work?

@blackfalcon This is a valid bug and this is NOT being addressed in the upcoming release.

**Comment by blackfalcon** [comment]
@Patrick-Daly-AA I am removing my name on this one. Please work with the devs to get this issue scheduled.

**Comment by Patrick-Daly-AA** [comment]
Design best practice is to not use a date picker for birthdate entry.  Navigating beyond the calendar start or end date on mobile would be a new feature request.
