### ISSUE TITLE
As a developer I need help with the placement of the calendar in the auro-datepicker

### ISSUE THREAD

**Issue by cynthiaricomendoza-alaskaair** [AlaskaAirlines/auro-datepicker#175]
# General Support Request
When testing my changes locally (relating to the auro-datepicker) on my mobile device in our check-in summary page, I noticed that the auro-datepicker isn't positioned correctly, it floats on top of the datepicker rather than taking up the whole screen.

## Support request
here is a screen recording of the behavior I am seeing on our check-in summary page

https://github.com/AlaskaAirlines/auro-datepicker/assets/116121736/57574ddd-8c06-4325-a5b3-ca6dea0f0d7b

I would expect the calendar to extend to fit the entire screen but that is not the behavior i am seeing. The reason I didn't submit a bug is because I've seen it work as expected on alaskaair.com/search, so I'm wondering if there some styles or dependencies that we are missing?

## Possible Solution

the auro-datepicker is inside a component on our check-in summary page, so i wonder if the styles needs to be updated to no matter where the datepicker is on the page, make sure the calendar extends to the whole page? or keep it how it was in v1.2.9 where the calendar appears below the input, like so:
![Screenshot 2023-12-13 at 17 38 17](https://github.com/AlaskaAirlines/auro-datepicker/assets/116121736/ba6cc2ac-d4a9-45dc-a5b7-43ca1fdf7de0)

## Context

This issue is preventing us from completing our sprint goals since we cannot move forward with this story with this mobile issue. We are hoping to get some guidance on how we can resolve this.

## Your Environment

* Version used: 2.0.10
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): iOS, iPhone
* Link to your project:

**Comment by blackfalcon** [comment]
@cynthiaricomendoza-alaskaair that is interesting. I am curious if this is a side-effect of the modal experience being triggered from inside an accordion which has its own positioning. 

I do know that we have a HUGE PR in the works that addresses multiple UI issues. 

- https://github.com/AlaskaAirlines/auro-datepicker/pull/172

@jordanjones243 do you have any insight on this issue or how this may be addressed with the upcoming updates?

**Comment by blackfalcon** [comment]
@jordanjones243 and @jason-capsule42 can you please validate if this issue still exists with all the updates we have released since this issue was created.

**Comment by Patrick-Daly-AA** [comment]
This is an old bug, but we still would like to validate the use case of a datepicker inside of an accordion on mobile, especially after the floating UI Changes we are working on.

**Comment by Patrick-Daly-AA** [comment]
Confirmed, this is still an issue with a datepicker inside an accordion.

**Comment by jason-capsule42** [comment]
This is no longer an issue due to we switched that mobile datepicker view is a full screen modal view.
