### ISSUE TITLE
Design token needed for themeing

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-datepicker#180]
### Please verify the version of auro-datepicker you have installed

@latest

### Please describe the bug

https://github.com/AlaskaAirlines/auro-datepicker/blob/9b2d32e1a0f57a2ba342f2a0ca8d23491b3f8ff5/src/style-auro-calendar-cell.scss#L169

### Reproducing the error

This issue is reproducible on the Auro docsite

### Expected behavior

This will need to be a design token so that we can theme it.  Given the comment it sounds like a perfect opportunity to explore a tier 3 token

### Exit criteria

This has been updated to a token value.

**Comment by blackfalcon** [comment]
I updated this from a `bug` to a `performance` update as the code deployed works as expected.

**Comment by blackfalcon** [comment]
@jason-capsule42 and @jordanjones243 can you please document what the 'problem' was that you refer to in this comment? 

> this token was part of the design but caused a problem with the `inRange` date styles so we had to switch to a solid color for hover.

**Comment by blackfalcon** [comment]
From what I can see, we currently do NOT have a baseline color token for #f0f0f0. 

@leeejune can we update this color used here to use a baseline color that is currently supported? 

I would stress that we not quickly jump to the tier 3 level of tokens as a solution as this comes with additional complexities for theming. I do think that we could have a tier 2 token for this background use, but that should never introduce a new value, but rather alias a base token. 

**Recommendation**: update this color to use a currently existing baseline token. Create a new semantic token, if needed, and update this element’s Sass.

**Comment by blackfalcon** [comment]
If new token work is required, we will need to create a new issue for that update.
