### ISSUE TITLE
Date Picker 2.1.1 depends on out of date version of webcorestylesheets

### ISSUE THREAD

**Issue by jessieiswise** [AlaskaAirlines/auro-datepicker#184]
### Please verify the version of auro-datepicker you have installed

2.1.1

### Please describe the bug

In a recent dependabot update, we noticed that the date picker is relying on ^4.2.0 of webcorestylesheets, while other Auro components rely on a later version. Here is the log:

'Log files:
/home/node/.npm/_logs/2024-01-08T15_54_38_581Z-debug-0.log

# npm resolution error report

While resolving: @aurodesignsystem/auro-badge@2.3.1
Found: @aurodesignsystem/webcorestylesheets@4.8.0
node_modules/@aurodesignsystem/webcorestylesheets
  dev @aurodesignsystem/webcorestylesheets@"^4.2.0" from the root project
  peer @aurodesignsystem/webcorestylesheets@"^4.2.0" from @aurodesignsystem/auro-datepicker@2.1.1
  node_modules/@aurodesignsystem/auro-datepicker
    dev @aurodesignsystem/auro-datepicker@"^2.1.1" from the root project

Could not resolve dependency:
peer @aurodesignsystem/webcorestylesheets@"^5.0.4" from @aurodesignsystem/auro-badge@2.3.1
node_modules/@aurodesignsystem/auro-badge
  dev @aurodesignsystem/auro-badge@"^2.3.1" from the root project

Conflicting peer dependency: @aurodesignsystem/webcorestylesheets@5.0.5
node_modules/@aurodesignsystem/webcorestylesheets
  peer @aurodesignsystem/webcorestylesheets@"^5.0.4" from @aurodesignsystem/auro-badge@2.3.1
  node_modules/@aurodesignsystem/auro-badge
    dev @aurodesignsystem/auro-badge@"^2.3.1" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

### Reproducing the error

This issue cannot be reproduced on the Auro docsite

### Expected behavior

Package is installed and no dependency issues are found

**Comment by blackfalcon** [comment]
Assigned to an engineer to review and address.
