### ISSUE TITLE
Mobile devices: Unexpected numerical keyboard and same-day arrival pane shadow

### ISSUE THREAD

**Issue by arrenleung** [AlaskaAirlines/auro-datepicker#192]
### Please verify the version of auro-datepicker you have installed

2.2.2

### Please describe the bug

*Both bugs are only visible when interacting with the datepicker on a real mobile device. Screenshots can be found below.*

### 1. Unexpected numerical keyboard

- Go to [the datepicker docsite](https://auro.alaskaair.com/components/auro/datepicker) and tap on a datepicker (single date or date range will produce the bug)
- See a numerical keyboard appear and caret overlay the calendar
- Invalid dates are able to be inputted this way (e.g. 09/09/9999) even with minDate/maxDate set

### 2. Same-day arrival pane shadow

- Go to [the datepicker docsite](https://auro.alaskaair.com/components/auro/datepicker) and tap on the ranged datepicker
- Select the same date for both departing and returning dates
- See the ranged shadow appear to the left and bottom of the pane

![image](https://github.com/AlaskaAirlines/auro-datepicker/assets/43892293/5d1a2c0c-7061-44ab-8d68-407de4c75620)

### Reproducing the error

This issue is reproducible on the Auro docsite

### 1. Unexpected numerical keyboard

Keyboard does not open and caret is not visible

### 2. Same-day arrival pane shadow

Selecting the same date for departing and returning dates does not render a shadow to the left and below the pane

### What browsers are you seeing the problem on?

Chrome, Safari

### Exit criteria

Same as expected behavior

**Comment by blackfalcon** [comment]
@jordanjones243 can you please put a comment in here as to why this is now `blocked`. Thanks.

**Comment by jordanjones243** [comment]
@blackfalcon This PR is blocked because it's code changes rely on this PR in auro-input to get released:
- https://github.com/AlaskaAirlines/auro-input/pull/286

**Comment by jordanjones243** [comment]
Issue is being re-opened, as the keyboard issue still persists.

**Comment by jordanjones243** [comment]
Bug no longer persists.
