### ISSUE TITLE
Emit events when opening calendar popover and navigating calendar months

### ISSUE THREAD

**Issue by arrenleung** [AlaskaAirlines/auro-datepicker#195]
### Is your feature request related to a problem? Please describe.

Flight search is beginning work on adding low fare pricing to the datepicker calendar, but there seems to be limitations when it comes to knowing when the calendar is opened and when the calendar months are being navigated.

Having awareness of these two events would allow us to make smaller requests to the CalendarAPI and prevent any unnecessary requests for dates that the user hasn't navigated to.

### Describe the solution you'd like

To add low fare pricing functionality to the datepicker calendar slots, we will need to know when:

- The calendar popover is opened and what MM/YYYY is first visible
  - Allows us to make the first initial pricing request to populate all visible dates 
- When the calendar months are navigated forward/backward and what MM/YYYY is now visible
  - Allows us to make new requests for dates that have not been populated yet

### Describe alternatives you've considered

None that are as straightforward...

### Exit criteria

- An event is emitted when the calendar popover is opened and contains details about the current month and year visible
- An event is emitted when the calendar months are navigated forward and backward containing details about the new month(s) visible

**Comment by blackfalcon** [comment]
This issue needs to be triaged as the team has not yet had a chance to review. But there is already a PR available for review from @arrenleung
