### ISSUE TITLE
Popovers intermittently stay open, popovers render behind second month on ranged datepicker

### ISSUE THREAD

**Issue by arrenleung** [AlaskaAirlines/auro-datepicker#197]
### Please verify the version of auro-datepicker you have installed

2.2.7

### Please describe the bug

Popovers intermittently stay open:

1. Go to [the docsite](https://auro.alaskaair.com/components/auro/datepicker/api) and scroll to the "Dynamic slot content" API example
2. Open the datepicker calendar
3. Move your cursor left and right over the dates with popovers
4. See that some popovers will stay open after your cursor leaves the calendar:
![image](https://github.com/AlaskaAirlines/auro-datepicker/assets/43892293/463e4daf-28ef-4a9f-93f8-6df423927171)

Popovers render behind second month on ranged datepicker:

1. Create a ranged datepicker component and populate each date with a popover span
2. Open the datepicker calendar and hover over the right-most dates in the left calendar
3. See that the popover opens behind the right calendar:
![image](https://github.com/AlaskaAirlines/auro-datepicker/assets/43892293/cbe360bc-a82d-4409-97d4-60e41e192649)

### Reproducing the error

This issue is reproducible on the Auro docsite

### Expected behavior

- Popovers close after the mouse leaves the date pane
- Popovers render over both calendars in ranged datepickers

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

**Comment by Patrick-Daly-AA** [comment]
note for fixing: look at the fix in dropdown that addresses a similar issue to this (clicking outside, rather than mouse-over outside)

**Comment by blackfalcon** [comment]
@jesussilverioea can you verify with other users on your team the first issue you are reporting with the dynamic content slot? I tested this in the latest Chrome, Safari, Edge and Firefox on macOS and am unable to repro this issue. Please see attached Gif. 

You stated in the issue that you are using v2.2.7, have you tried [v2.3.0](https://github.com/AlaskaAirlines/auro-datepicker/releases/tag/v2.3.0)? What OS are you using? 

![Mar-05-2024 08-03-50](https://github.com/AlaskaAirlines/auro-datepicker/assets/181089/8d209ebe-b827-4e11-b08f-ab0aab86e74d)

**Comment by blackfalcon** [comment]
It's been noted that there is a use case where a user would have to move across the UI at an accelerated rate to trigger this issue. That is confirmed.

**Comment by jordanjones243** [comment]
This change in `auro-popover` will fix the first bug in this issue:
- https://github.com/AlaskaAirlines/auro-popover/pull/61
