### ISSUE TITLE
Automatically rerender date panes when price/popover spans are added

### ISSUE THREAD

**Issue by arrenleung** [AlaskaAirlines/auro-datepicker#198]
### Is your feature request related to a problem? Please describe.

When implementing lowest-cost pricing to the datepicker, we will have to wait until the user opens the calendar before we make any requests for prices to prevent unnecessary API calls.

Because of this, we add price/popover spans to the datepicker only after the user opens the calendar and we get a response back, all while the calendar is still open. Currently, we need to either close and reopen the calendar or hover over a date in order for the panes to rerender with the added spans.

### Describe the solution you'd like

Date panes are aware when a price and/or popover span is added to the datepicker and rerenders without needing any user interaction.

### Describe alternatives you've considered

We can rerender the entire datepicker component when we add the spans, but this will cause the datepicker to close and require the user to reopen the calendar again, making it a frustrating user experience.

**Comment by Patrick-Daly-AA** [comment]
We are currently unsure the reasoning behind this behavior not working.  @jason-capsule42 will reach out and investigate with you further since knowing about the specific implementation in this case will greatly help understanding how to address this.
