### ISSUE TITLE
Recent changes in auro-input cause border UI error

### ISSUE THREAD

**Issue by jordanjones243** [AlaskaAirlines/auro-datepicker#212]
### Please verify the version of auro-datepicker you have installed

2.4.1

### Please describe the bug

1. Open `auro-datepicker` repo locally
2. Update to latest version of `auro-input`
3. Run localhost

### Reproducing the error

This issue cannot be reproduced on the Auro docsite

### Expected behavior

Border UI looks same as after update

### What browsers are you seeing the problem on?

Chrome

### Additional context

<img width="1171" alt="Screen Shot 2024-04-05 at 1 12 15 PM" src="https://github.com/AlaskaAirlines/auro-datepicker/assets/55807669/ef86b6e1-901b-46ba-830b-acef3ecd16ae">

### Exit criteria

When border UI reverts back to original state outline in the blueprint, this issue can be considered fixed

**Comment by Patrick-Daly-AA** [comment]
This issue only existed on a branch and has been addressed on that branch.
