### ISSUE TITLE
Update version files with the remote build

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-datepicker#219]
### General Support Request

I noticed with the last release that the version files created with the build were not updated. This is an easily missed step while in dev. 

Running a build post the latest released, I noticed these updated files. 

```
	modified:   src/dropdownVersion.js
	modified:   src/inputVersion.js
```

### Possible Solution

Update the `assets` config in the package.json to support these updated files in the remote build to be committed back to the repo with the version update. 

```json
          "assets": [
            "./package.json",
            "./CHANGELOG.md",
            "./README.md",
            "./docs/api.md",
            "./demo/demo.md",
            "./demo/api.md"
          ]
```

### Additional context

n/a

### Exit criteria

This issue can be closed once the repo is updated to support committing these files back to the repo from the remote build.

**Comment by Patrick-Daly-AA** [comment]
Issue doesn't repro when doing a clean pull of the main branch.  closing.

**Comment by blackfalcon** [comment]
Because there is a dependency on running a build POST an update, not everyone will run builds locally when running updates. If not, then these files will be out of sync. They shouldn't rely on a manual step to be correct.
