### ISSUE TITLE
auro-datepicker: [Mobile] The range date picker flickers and does not fill in the return date after re-selecting the date

### ISSUE THREAD

**Issue by trupti-alaskaair** [AlaskaAirlines/auro-datepicker#227]
### General Support Request

Howdy? Another weird Android issue.  The best way to explain the issue is through a couple of videos we recorded over saucelabs because it's hard to explain in words what the issue is!  Attached is the video and below are the exact repro steps because they might not be clear from the video although the problem is very clear:

1. Open up the Auro component in SauceLabs and click the range datepicker component's "fromLabel" slot on the UI.  Click on a date say 30th of May.
2. Then, click on the 21st of May (any date prior to the fromLabel date).  The date should start flickering on the calendar
3. If it doesn't, then click now on a date after 30th of May.  The date definitely starts flickering and toggling between the 21st and 30th.  
4. click "Done" on the calendar, and observe the Return label field, it keeps fluctuating and flickering too.

https://github.com/AlaskaAirlines/auro-datepicker/assets/162357927/6395308c-ea95-478c-a772-a652d6cff960

### Possible Solution

When we checked the dev-tools i observed that the random ids assigned to the auro components fromLabel and toLabel keep changing, and we are stuck in an infinite loop.  The issue occurs before the flickering occurs.  

We just noticed that as soon as we pick a return date that's earlier than the departure date on the date range picker the ids on the both auro-inputs of the auro-dropdown component keep changing the randomly assigned ids constantly as observed on the Elements in the dev-tools.  Also, the valueEnd on the range date picker is not set as it does on a normal browser.

### Additional context

Any additional information can be found at : [Bug 1042895](https://itsals.visualstudio.com/E_Sell_Shop/_workitems/edit/1042895): Mobile App and Browser: Datepicker UI issues with RT Selection - Android Only

**Comment by Patrick-Daly-AA** [comment]
Bug seems to repro on Chrome and Edge Browsers on mobile.
