### ISSUE TITLE
auro-datepicker: Option to highlight specific price slots

### ISSUE THREAD

**Issue by arrenleung** [AlaskaAirlines/auro-datepicker#241]
### Is your feature request related to a problem? Please describe.

When populating all date slots with prices on the calendar, it can take a little more time to find the lowest price since all date slots share the same text styles.

![image](https://github.com/AlaskaAirlines/auro-datepicker/assets/43892293/b43b3092-c3ea-428b-8f30-1b053207d003)

### Describe the solution you'd like

It'd be ideal for date slots to consume an attribute to highlight its text like so:
```html
<span slot="date_12_05_2023">$100</span>
<span slot="date_12_06_2023">$2345</span>
<span slot="date_12_07_2023">$149</span>
<span slot="date_12_04_2023" highlight>$89</span> <!-- Highlighting the lowest price -->
<span slot="date_12_08_2023">$382</span>
<span slot="date_12_09_2023">$560</span>
```
but the specific styles that would apply to highlighted date slots is up to designers.

### Describe alternatives you've considered

Using in-line styles on the date slots to change the text color, but this overwrites ALL color styles and won't apply the relavant styles when the pane is selected, disabled, or hovered over.

**Comment by Patrick-Daly-AA** [comment]
Sending for Design review to determine what we want a highlighted date to look like for this sort of situation.  Especially we want to ensure alignment on approach, look, and feel with regards to low fare calendar.

**Comment by leeejune** [comment]
I think we should have the team talk about this feature as a whole before going into design solutions. I will be there for Monday's standup. 

@Patrick-Daly-AA can we go over this together?

**Comment by erikalanghauser** [comment]
I revisited some old date picker research. Using blue as an indicator of a low fare is not clear to guests and several interpreted gray pricing as unavailable. So those are big issues. I think green better indicates low price and is consistent with the low fare alert badge they will see on flight results. 

Here is the design recommendation I provided @arrenleung for indicating the low fare:
Update all the default blue prices to --ds-color-text-primary-default, and just change the lowest price to --ds-color-text-success-default. If a lowest price is selected, the green text will flip to white, just like it does in a selected state today.

Before:
![image](https://github.com/user-attachments/assets/b3a52f46-5a27-4360-9f7a-fd12ddc56575)

After:
![image](https://github.com/user-attachments/assets/c8a187a5-755d-4712-90c3-2c275fc11e8e)

Please let us know if we can continue forward with these tokens in the implementation, or if we need to discuss the design further. Thanks.
