### ISSUE TITLE
auro-datepicker: Don't move month from right pane to left pane mid-date range selection

### ISSUE THREAD

**Issue by erikalanghauser** [AlaskaAirlines/auro-datepicker#246]
### Is your feature request related to a problem? Please describe.

When searching for a round trip flight, and going to select a date range in a month that is location on the right side of the pane...
For example, today is July 25, so selecting a date range in August:
![image](https://github.com/user-attachments/assets/7a4fd21c-7a4b-405d-a05b-e8c5a74d37d3)

When I select the departing date in August from the right pane, the month of August then pops over to the left pane, and now I have to go hunt down the returning date on the other pane, when my cursor was just near my desired date a second ago.
![image](https://github.com/user-attachments/assets/29f674f4-e3d8-493c-8743-c515d7c53142)

### Describe the solution you'd like

If I click on a departing date with the month in the right pane, have the month stay put. Do not have the month move over to the left pane. This will allow for a much quicker and less jarring experience.

### Exit criteria

When I select a departing date in the right pane, there is no movement of months or dates to the left pane. The calendars stay put until I finish my selection (unless of course, I click an arrow to scroll the month forward or back).

**Comment by Patrick-Daly-AA** [comment]
Going to have some further discussion about the UX impacts of this change, since we feel there is a similarly strong case for leaving the behavior as it currently is.

**Comment by Patrick-Daly-AA** [comment]
Confirmed from Design discussion that panes should not move when a date is clicked on in the calendar.  However, it is noted that panes _should_ move if a date is typed in that is not currently visible.
