### ISSUE TITLE
React.js apps: Datepicker input not styled correctly

### ISSUE THREAD

**Issue by tjgrist** [AlaskaAirlines/auro-datepicker#34]
## Describe the bug

React apps cannot seem to render the date-picker, whereas all other Auro components that we've used do render correctly. I've tried adding the date-picker to our create react app microsite, and it appears to be added to the DOM, but doesn't render correctly with styles, icons, and the dropdown doesn't open.
<img width="1673" alt="Screen Shot 2022-07-27 at 11 13 04 AM" src="https://user-images.githubusercontent.com/17755678/181343055-950c41c7-0e94-4881-a161-bf8283ccdf41.png">

## To Reproduce

Download this create react app repo: https://github.com/tjgrist/my-app and run it. You cannot open the date-picker, it appears only the 'Choose date' text displays. 
<img width="1513" alt="Screen Shot 2022-07-27 at 11 08 52 AM" src="https://user-images.githubusercontent.com/17755678/181342382-bcd0815c-8d82-4f33-9a2a-ce0387ce34a4.png">

1. Download the repo
2. Install the packages
3. Run the project
4. Open localhost:3000
5. Click on the date-picker

## Expected behavior

Date-picker should display as it does on the auro demo page, and should have icons/styles and should show the calendar dropdown when you click it. 

## Screenshots

See shots above

## Desktop (please complete the following information):

 - OS: MacOS
 - Browser Brave, Chrome, Firefox
 - Version Latest

## Additional context

N/A

**Comment by braven112** [comment]
Have you tried to include the calendar npm package or cdn link?

**Comment by braven112** [comment]
@tjgrist  I had a chance to look at the code and see that calendar isn't added.  I ran into the same issue when I first tried to use it.  We should update our documentation to make that more clear. 

If it turns out there is another issue though please let me know.

**Comment by tjgrist** [comment]
We're trying to install the peer dependencies for auro-calendar, auro-dropdown, etc. But those weren't listed as required installation dependences. What other dependencies -- including css -- might we need? @braven112

**Comment by tjgrist** [comment]
Adding auro-calendar and auro-input seems to work, but the styles aren't right. What am I missing? 
![Screen Shot 2022-07-27 at 4 41 04 PM](https://user-images.githubusercontent.com/17755678/181391512-84a953ad-f395-4c96-b9a6-336261898328.png)

![Screen Shot 2022-07-27 at 4 50 10 PM](https://user-images.githubusercontent.com/17755678/181391553-b096308e-3460-4f27-bdec-5787f722c7b0.png)

**Comment by tjgrist** [comment]
I see that the first pic may be the z-index [issue](https://github.com/AlaskaAirlines/auro-datepicker/issues/32)

**Comment by braven112** [comment]
> We're trying to install the peer dependencies for auro-calendar, auro-dropdown, etc to make it render properly now, will update. But those weren't listed as required installation dependences. What other dependencies -- including css -- might we need? @braven112

@jason-capsule42 is going to work on updating the docs with the correct peer dependencies. It doesn't sound like you need anymore case files if you have wcss and design tokens.

**Comment by braven112** [comment]
> I see that the first pic may be the z-index [issue](https://github.com/AlaskaAirlines/auro-datepicker/issues/32)

#32 appears if you resize the browser window while the calendar is open. I think for you its missing a dependency but I'm not sure what one yet.

**Comment by blackfalcon** [comment]
Yes, we should have the docs illustrate this clearly. An example we should follow is what we did with https://auro.alaskaair.com/components/auro/flight/install

**Comment by tjgrist** [comment]
Updated the title to align with the remaining styling issue on the input element.

**Comment by blackfalcon** [comment]
@tjgrist following up on this... from what I can see, this issue was resolved by doing the correct install, right? Missing dependencies was the crux of the issue?

**Comment by braven112** [comment]
Closing this one as it appears to be an issue with the installation and we have created #35 to help with this.  If there is anything else please reopen this issue.

**Comment by tjgrist** [comment]
@blackfalcon @braven112 yes I figured it out... I needed to ensure I had all the other components installed: auro-calendar, auro-dropdown, and auro-input!
