### ISSUE TITLE
Let folks know to add auro-calendar

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-datepicker#35]
# General Support Request

Its not obvious that you need to add auro-calendar when using auro-datepicker.  I ran into this when I implemented it in a demo and I believe this is the problem brought up in this issue #34 

## Support request

Include auro-calendar instructions when viewing the datepicker so that folks know they need to include auro-calendar and auro-datepicker.

**Comment by tjgrist** [comment]
I believe in addition to auro-calendar users must have auro-input and auro-dropdown installed
