### ISSUE TITLE
dynamic and matching width layouts

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-datepicker#38]
## Is your feature request related to a problem? Please describe.

Currently the datepicker is a set width.  In order for it to be paired in a visually consistent way with other inputs it needs to be able to be as wide as its container.

![image](https://user-images.githubusercontent.com/5118118/180476791-cd3bebd9-7814-43b4-806d-899836df413b.png)

## Describe the solution you'd like

By default the datepicker works just like auro-input and spans the width of its container.

## Describe alternatives you've considered

Its possible this would require a rewrite of parts of this component.

## Additional context

Right now the input is set to inline-block.  Setting it to block means that the input is as wide as the calendar, so we'll need to figure out what the dropdown would look like if the input is wider than the calendar.

**Comment by jason-capsule42** [comment]
This will be fixed by: https://github.com/AlaskaAirlines/auro-dropdown/issues/141

Very it works correctly after that is released.
