### ISSUE TITLE
DatePicker re-render after the "value" parameter is changed.

### ISSUE THREAD

**Issue by jesussilverioea** [AlaskaAirlines/auro-datepicker#39]
## Is your feature request related to a problem? Please describe.

We would like the datepicker input box to re-render once the value change. In our case, we want to set the value for the second datepicker once we click on the first one. It is happening but the datepicker is not re-rendering.

![image](https://user-images.githubusercontent.com/108018885/182684850-d13efbf3-29d4-4ad8-a814-47dbb367fda1.png)
## Describe the solution you'd like

we would like the datepicker to re-render once the value of the "value" parameter changes. We believe a listener could be added to this parameter or the firstUpdate function could be modify in order to achieve this.

## Additional context

[Our Code](https://github.com/Alaska-ECommerce/flightsearch-lem-svelte/blob/jes/datepicker/src/lib/planbook/DatePicker.svelte#L59)

**Comment by braven112** [comment]
@jesussilverioea I wasn't able to repro this issue on https://www.alaskaair.com/search-test/  has anything changed since this issue was created?

**Comment by braven112** [comment]
@jesussilverioea It looks like you were able to fix this on your end. Let us know if we need to reopen this issue.

**Comment by jesussilverioea** [comment]
yes! we were able to fix it in our end. Thank you for looking into this tho. 👍
