### ISSUE TITLE
Typing in a valid date returns NaN/NaN/NaN

### ISSUE THREAD

**Issue by shonore-aa** [AlaskaAirlines/auro-datepicker#42]
## Describe the bug

If you focus in on the Datepicker and quickly type in a valid date from the past formatted as MM/DD/YYYY then the value NaN/NaN/NaN will populate the field. 

## To Reproduce
1. Set a min date for the Datepicker as today
2. Focus in on the Datepicker component
3. Type in 08/19/2019 quickly
4. The value "NaN/NaN/NaN" populates the field

## Expected behavior

The value "NaN/NaN/NaN" should not populate the field and the value that the user typed in should populate the field

## Screenshots

![Screen Shot 2022-08-16 at 4 21 15 PM](https://user-images.githubusercontent.com/107429014/184988192-b016884a-8a97-4c39-9da8-22dbe8053140.png)
![Screen Shot 2022-08-16 at 2 44 03 PM](https://user-images.githubusercontent.com/107429014/184988201-d5cc21eb-c206-47f8-b0ea-47f9bdc6d843.png)

## Desktop (please complete the following information):

 - OS: Mac OS
 - Browser: Chrome
 - Version: latest

## Smartphone (please complete the following information):

 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Comment by blackfalcon** [comment]
I feel that there is an implementation issue here. While I can repo this issue in the demo you created, I am unable to have this happen with the demo here https://auro.alaskaair.com/components/auro/datepicker

@jason-capsule42 can you confirm this?

**Comment by braven112** [comment]
I was able to repro this sometimes on this page https://auroized-fly-website.surge.sh/ by typing in an date in the past.
