### ISSUE TITLE
Inconsistent date formatting

### ISSUE THREAD

**Issue by shonore-aa** [AlaskaAirlines/auro-datepicker#44]
## Describe the bug

When you select a date from the calendar the input field is populated with a date in the format M/D/YYYY. When you type in a date the input field only accepts MM/DD/YYYY. 

## To Reproduce

1. click on the datepicker field
2. select a date with a single digit month and day
3. The date that populates the input field is formatted as M/D/YYYY
4. Now clear the field
5. type in a date value with a single digit month and a single digit date
6. the expected formatting is now MM/DD/YYYY

## Expected behavior

The user should be able to specify the date format that they need and then selecting and typing in a value should utilize the same date format. 

## Screenshots

![Screen Shot 2022-08-16 at 5 43 53 PM](https://user-images.githubusercontent.com/107429014/184997900-b27b47fc-5e65-409f-9289-088080ca1c79.png)

## Desktop (please complete the following information):

 - OS: MacOS
 - Browser chrome
 - Version latest

## Smartphone (please complete the following information):

 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Comment by blackfalcon** [comment]
Validated with https://auro.alaskaair.com/components/auro/datepicker demo. 

The date value in the UI should be consistent with the pattern we have in the placeholder.
