### ISSUE TITLE
Datepicker calendar flickers behind element before dismissed

### ISSUE THREAD

**Issue by vhdinh** [AlaskaAirlines/auro-datepicker#57]
## Describe the bug
Datepicker calendar flickers behind element before dismissed

## To Reproduce
on https://auro-prod-site-w2.azurewebsites.net/components/auro/datepicker
- scroll down to where calendar overlays tabs
- close calendar, 

on Auro site
1. go to https://auro-prod-site-w2.azurewebsites.net/components/auro/datepicker
2. scroll down to where calendar overlay would be on top of nav tabs (Datepicker, Install, API, etc)
3. click on datepicker input to open calendar
4. click outside to close datepicker
on https://www.alaskaair.com/search-qa/
1. go to https://www.alaskaair.com/search-qa/
2. click on either Departing or Returning datepicker
3. click somewhere on the page to dismiss the datepicker

## Expected behavior
datepicker calendar should dismiss without having some weird flickering/z-index 

## Screenshots
auro site:
https://user-images.githubusercontent.com/13775747/189238821-99221e98-6f1a-4b38-9f59-99802097872f.mov
as.com - qa
https://user-images.githubusercontent.com/13775747/189238853-346811cb-5049-4a73-afea-488a6d1d25a0.mov

## Desktop (please complete the following information):

 - OS: Mac iOS
 - Browser: chrome(Version 105.0.5195.102), firefox(104.0.2), safari(v15.6)

**Comment by blackfalcon** [comment]
This is an interesting bug. I see what you are talking about in the attached videos, but I am unable to repro. Are there others on your team that can confirm?

**Comment by jason-capsule42** [comment]
I am unable to reproduce this bug.

**Comment by blackfalcon** [comment]
Confirmed, unable to repro this issue. @vhdinh can you validate your repro criteria?

**Comment by jordanjones243** [comment]
Completed further validation testing and I am also unable to repro this bug. This ticket is being closed.
