### ISSUE TITLE
Button Hitbox and Miss-click Effects

### ISSUE THREAD

**Issue by ftaylor-alaska** [AlaskaAirlines/auro-datepicker#61]
## Describe the bug

When selecting a date, if the user selects anything but the button of a date, it will reset the component. Furthermore, the hitbox of the button is much smaller than the surrounding area, so there is a lot of deadspace which compounds this effect making it happen often.

## To Reproduce

1. Open the calendar and scroll to another month.
2. Click an area between two dates
3. The calendar will reset to the original month

## Expected behavior

1. If a guest selects something within the calendar then nothing should happen. 
2. There should be 0 pixels in between dates hitbox so that when a guest clicks near a date the closest one is chosen.

## Screenshots
* The clickable area is highlighted in red in the following video to show where the only "safe" places are to click:  

https://user-images.githubusercontent.com/51933786/191630387-e55e1d25-513b-45a7-a324-176e4c6de1e3.mp4

**Comment by blackfalcon** [comment]
@ftaylor-alaska please see if you can repro this on the docsite https://auro.alaskaair.com/components/auro/datepicker

I believe some recent updates may have corrected this issue. Now, if you click between dates, the dropdown bib closes. 

Note, with the screenshot, the target area exceeds the minimum target size for AAA WCAG standard https://dequeuniversity.com/resources/wcag2.1/2.5.5-target-size

<img width="678" alt="Screen Shot 2022-09-22 at 8 35 12 AM" src="https://user-images.githubusercontent.com/181089/191790496-42feea94-9f2d-415a-a6cb-402448cbe5a7.png">

**Comment by ftaylor-alaska** [comment]
This can be reproduced on the docsite. I will use the docsite moving forward for any examples

**Comment by braven112** [comment]
@ftaylor-alaska our recent changes to auro-datepicker seem to have fixed the issue where the datepicker resets when a user clicks outside of a date.  I'm not able to repro in chrome on a pc.  Are you able to repro this still?

**Comment by blackfalcon** [comment]
Current screen capture. Unable to repro the issue. Clicking in dead spaces around date buttons DOES NOT close the calendar bib.

![Sep-30-2022 09-48-15](https://user-images.githubusercontent.com/181089/193318707-b48beb62-0230-4d26-97aa-1a99e31c12cd.gif)
