### ISSUE TITLE
Borders are not rounded in focus and error states in Safari

### ISSUE THREAD

**Issue by jordanjones243** [AlaskaAirlines/auro-datepicker#87]
## Describe the bug

The border corners of the element are not rounded in Safari when the element is in a focus or error state.

## To Reproduce

1. Go to https://auro.alaskaair.com/components/auro/datepicker
1. Click on any example
1. See error

## Expected behavior

Border corners are rounded.

## Desktop (please complete the following information):

 - Browser: Safari

## Additional context

This is a bug for all of our form elements, refer to this initial ticket opened in `auro-input`:
- https://github.com/AlaskaAirlines/auro-input/pull/208

**Comment by blackfalcon** [comment]
This issue is specific to Safari due to the fact that Safari does not support rounding of outlines vs borders. This is a low-priority issue.

**Comment by braven112** [comment]
Need to look at either using outline or box shadow to get around the safari issue.  We fixed this in dropdown so use that as an example.

**Comment by blackfalcon** [comment]
@jdeeezzy this is closed without a comment as to why or a link to a closed PR. What is the status of this issue?

**Comment by blackfalcon** [comment]
After reviewing this issue, it appears to be fixed in Safari. When and how... ¯\_(ツ)_/¯ 

![Screen Shot 2023-01-20 at 3 19 02 PM](https://user-images.githubusercontent.com/181089/213822017-460a37c6-89e4-48ae-9da5-97ae81f3b50a.png)
