### ISSUE TITLE
Handle removing the `error` attribute before a value is applied to the element

### ISSUE THREAD

**Issue by jason-capsule42** [AlaskaAirlines/auro-datepicker#92]
## Describe the bug

Validity is only run when a value is set. This creates an issue where if a custom `error` attribute is applied before the value is set, and then the `error` attribute is removed, the validity check is not executed and the element is not returned to it's original state.

## To Reproduce

1. Run a demo example where the `error` attribute is preset but there is no value set.
1. In the debugger remove the `error` attribute
1. See that the `validity` is not reset

## Expected behavior

Validity should be reset in this scenario.

**Comment by blackfalcon** [comment]
@jason-capsule42 please add an exit criterion to this issue prior to starting work.
