### ISSUE TITLE
Dates unselectable in datepicker causing guest frustration

### ISSUE THREAD

**Issue by erikalanghauser** [AlaskaAirlines/auro-datepicker#96]
## Describe the bug

Multiple guest and internal issues with selecting a date from the date picker both in the flight search widget and on the auro doc site.

6 users out of 15 users were unable to click on the date picker for their roundtrip flight. Some resorted to manually typing in the dates to get the search to function, and others gave up altogether for those dates. All 15 users were on Chrome, the 6 users with issues were on a Mac, and the 9 users who did not have the issue were on Windows.

## To Reproduce

Here is a clip of some of the participant difficulty selecting calendar dates: https://app.usertesting.com/h/2q5vbJQQdfcMuCaFyJRi?shared_via=link&shared_via=link

## Expected behavior

Guests should be able to select a date regardless of other ongoing activity on their browser or device. They should not have to resort to typing it in.

## Screenshots

See videos linked above.

## Desktop (please complete the following information):

Reproduced on multiple devices via usertesting.

## Additional context

Going to add @aesthetiques to the convo so he can add any findings that he had on the auro doc site.

**Comment by blackfalcon** [comment]
I believe that this issue was addressed with the v1.2.7 release, specifically this issue 

- https://github.com/AlaskaAirlines/auro-datepicker/issues/93

**Comment by blackfalcon** [comment]
This issue will remain open until it is verified by @erikalanghauser that upgrading to v1.2.7 has fixed the reported issue.

**Comment by jesussilverioea** [comment]
Issue seems to be resolved.

**Comment by isaiahscheel** [comment]
@blackfalcon 

Just got a new session of prod and still running into this issue. We are confirmed on version 1.2.7 now in prod but still running into the issue: 

https://user-images.githubusercontent.com/40191651/214368324-605a0526-8eda-444e-9150-f8eee693c745.mov

**Comment by erikalanghauser** [comment]
@blackfalcon can we reopen this issue please? It does not appear to be resolved.

![Snip20230124_100](https://user-images.githubusercontent.com/34354487/214447071-33a7fa62-16de-4721-8542-a0ad9ce2a3ae.png)

Today's date (Jan 24) is highlighted as though it is selected upon opening the Returning calendar even though the field reads '01/26/2023' and it is earlier than the Departing date I selected (Jan 26). I was then unable to select a new date (Jan 30).

**Comment by jason-capsule42** [comment]
This is a different issue than the previous issue where the chrome browser was pausing the JS of background tabs and that was breaking the datepicker.

I have opened https://github.com/AlaskaAirlines/auro-datepicker/issues/99.
