### ISSUE TITLE
Datepicker not receiving the "required" parameter

### ISSUE THREAD

**Issue by jesussilverioea** [AlaskaAirlines/auro-datepicker#97]
## Describe the bug

The datepicker is not taking the "required" field that would not show the "(optional)" word in the datepicker.

![image](https://user-images.githubusercontent.com/108018885/213840324-e9588486-cc2a-4f3d-a07e-b0d2f03967a0.png)

## To Reproduce

got to the auro webpage under the required field.
https://auro.alaskaair.com/components/auro/datepicker/api

## Expected behavior

passing the `required` parameter should not show "(optional)" on the datepicker box.

This is how it was in the previous version:

![image](https://user-images.githubusercontent.com/108018885/213840446-b4eaae0b-aba9-42a2-a709-d5e54134c974.png)

**Comment by jordanjones243** [comment]
This ticket has been re-opened to fix the semantic release versioning, which previously caused this fix to fail when trying to publish.
